version: "2"

services:

### Applications Code Container #############################

    applications:
      volumes:
        - ${APPLICATION}:/var/www
    sails:
      volumes:
        - ${SAILS_PATH}:/var/www
    apache2:
      volumes:
        - ${FRONT_PATH}:/var/www
